### ISSUE TITLE
Exception while saving new annotation

### ISSUE THREAD

**Issue by pnrobinson** [pnrobinson/loinc2hpoMiner#10]
Unsure why we are tyring to read the file in when the user presses save -- something is miswired.
```
Loinc2HpoRuntimeException: Malformed line with 8 fields: 600-7	s	NOMINAL	NEG	HP:0031864		HPO:nvasilevsky[2018-05-10]	.
	at org.monarchinitiative.loinc2hpocore.annotation.Loinc2HpoAnnotation.fromAnnotationLine(Loinc2HpoAnnotation.java:111)
	at org.monarchinitiative.loinc2hpocore.io.Loinc2HpoAnnotationParser.importAnnotations(Loinc2HpoAnnotationParser.java:44)
	at org.monarchinitiative.loinc2hpocore.io.Loinc2HpoAnnotationParser.<init>(Loinc2HpoAnnotationParser.java:31)
	at org.monarchinitiative.loinc2hpo.OptionalResources.getLoincAnnotations(OptionalResources.java:89)
```

**Comment by pnrobinson** [comment]
fixed
